// This file is generated by rust-protobuf 3.7.2. Do not edit
// .proto file is parsed by protoc --rs_out=...
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_results)]
#![allow(unused_mut)]

//! Generated file from `knowledge.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_3_7_2;

/// * Knowledge metadata. 
// @@protoc_insertion_point(message:fonts.KnowledgeProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct KnowledgeProto {
    // message fields
    /// * Module ids in order. 
    // @@protoc_insertion_point(field:fonts.KnowledgeProto.modules)
    pub modules: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.KnowledgeProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a KnowledgeProto {
    fn default() -> &'a KnowledgeProto {
        <KnowledgeProto as ::protobuf::Message>::default_instance()
    }
}

impl KnowledgeProto {
    pub fn new() -> KnowledgeProto {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "modules",
            |m: &KnowledgeProto| { &m.modules },
            |m: &mut KnowledgeProto| { &mut m.modules },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<KnowledgeProto>(
            "KnowledgeProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for KnowledgeProto {
    const NAME: &'static str = "KnowledgeProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.modules.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.modules {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.modules {
            os.write_string(1, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> KnowledgeProto {
        KnowledgeProto::new()
    }

    fn clear(&mut self) {
        self.modules.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static KnowledgeProto {
        static instance: KnowledgeProto = KnowledgeProto {
            modules: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for KnowledgeProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("KnowledgeProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for KnowledgeProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for KnowledgeProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// *
///  Knowledge module metadata.
///
///  <p>Module id is inferred from directory name in the filesystem.
// @@protoc_insertion_point(message:fonts.ModuleProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ModuleProto {
    // message fields
    // @@protoc_insertion_point(field:fonts.ModuleProto.alt_ids)
    pub alt_ids: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.ModuleProto.name)
    pub name: ::std::option::Option<::std::string::String>,
    /// * Brief description of the module. 
    // @@protoc_insertion_point(field:fonts.ModuleProto.excerpt)
    pub excerpt: ::std::option::Option<::std::string::String>,
    /// * Ids of constituent lessons in order. 
    // @@protoc_insertion_point(field:fonts.ModuleProto.lessons)
    pub lessons: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.ModuleProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ModuleProto {
    fn default() -> &'a ModuleProto {
        <ModuleProto as ::protobuf::Message>::default_instance()
    }
}

impl ModuleProto {
    pub fn new() -> ModuleProto {
        ::std::default::Default::default()
    }

    // optional string name = 2;

    pub fn name(&self) -> &str {
        match self.name.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_name(&mut self) {
        self.name = ::std::option::Option::None;
    }

    pub fn has_name(&self) -> bool {
        self.name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        if self.name.is_none() {
            self.name = ::std::option::Option::Some(::std::string::String::new());
        }
        self.name.as_mut().unwrap()
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        self.name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string excerpt = 3;

    pub fn excerpt(&self) -> &str {
        match self.excerpt.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_excerpt(&mut self) {
        self.excerpt = ::std::option::Option::None;
    }

    pub fn has_excerpt(&self) -> bool {
        self.excerpt.is_some()
    }

    // Param is passed by value, moved
    pub fn set_excerpt(&mut self, v: ::std::string::String) {
        self.excerpt = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_excerpt(&mut self) -> &mut ::std::string::String {
        if self.excerpt.is_none() {
            self.excerpt = ::std::option::Option::Some(::std::string::String::new());
        }
        self.excerpt.as_mut().unwrap()
    }

    // Take field
    pub fn take_excerpt(&mut self) -> ::std::string::String {
        self.excerpt.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(4);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "alt_ids",
            |m: &ModuleProto| { &m.alt_ids },
            |m: &mut ModuleProto| { &mut m.alt_ids },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "name",
            |m: &ModuleProto| { &m.name },
            |m: &mut ModuleProto| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "excerpt",
            |m: &ModuleProto| { &m.excerpt },
            |m: &mut ModuleProto| { &mut m.excerpt },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "lessons",
            |m: &ModuleProto| { &m.lessons },
            |m: &mut ModuleProto| { &mut m.lessons },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ModuleProto>(
            "ModuleProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ModuleProto {
    const NAME: &'static str = "ModuleProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.alt_ids.push(is.read_string()?);
                },
                18 => {
                    self.name = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.excerpt = ::std::option::Option::Some(is.read_string()?);
                },
                34 => {
                    self.lessons.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.alt_ids {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.excerpt.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        for value in &self.lessons {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.alt_ids {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.name.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.excerpt.as_ref() {
            os.write_string(3, v)?;
        }
        for v in &self.lessons {
            os.write_string(4, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ModuleProto {
        ModuleProto::new()
    }

    fn clear(&mut self) {
        self.alt_ids.clear();
        self.name = ::std::option::Option::None;
        self.excerpt = ::std::option::Option::None;
        self.lessons.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ModuleProto {
        static instance: ModuleProto = ModuleProto {
            alt_ids: ::std::vec::Vec::new(),
            name: ::std::option::Option::None,
            excerpt: ::std::option::Option::None,
            lessons: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ModuleProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ModuleProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ModuleProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ModuleProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// *
///  Knowledge topic metadata.
///
///  <p>Topic id is inferred from directory name in the filesystem.
// @@protoc_insertion_point(message:fonts.TopicProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TopicProto {
    // message fields
    // @@protoc_insertion_point(field:fonts.TopicProto.alt_ids)
    pub alt_ids: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.TopicProto.name)
    pub name: ::std::option::Option<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.TopicProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TopicProto {
    fn default() -> &'a TopicProto {
        <TopicProto as ::protobuf::Message>::default_instance()
    }
}

impl TopicProto {
    pub fn new() -> TopicProto {
        ::std::default::Default::default()
    }

    // optional string name = 2;

    pub fn name(&self) -> &str {
        match self.name.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_name(&mut self) {
        self.name = ::std::option::Option::None;
    }

    pub fn has_name(&self) -> bool {
        self.name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        if self.name.is_none() {
            self.name = ::std::option::Option::Some(::std::string::String::new());
        }
        self.name.as_mut().unwrap()
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        self.name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(2);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "alt_ids",
            |m: &TopicProto| { &m.alt_ids },
            |m: &mut TopicProto| { &mut m.alt_ids },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "name",
            |m: &TopicProto| { &m.name },
            |m: &mut TopicProto| { &mut m.name },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TopicProto>(
            "TopicProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TopicProto {
    const NAME: &'static str = "TopicProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.alt_ids.push(is.read_string()?);
                },
                18 => {
                    self.name = ::std::option::Option::Some(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.alt_ids {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.alt_ids {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.name.as_ref() {
            os.write_string(2, v)?;
        }
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TopicProto {
        TopicProto::new()
    }

    fn clear(&mut self) {
        self.alt_ids.clear();
        self.name = ::std::option::Option::None;
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TopicProto {
        static instance: TopicProto = TopicProto {
            alt_ids: ::std::vec::Vec::new(),
            name: ::std::option::Option::None,
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TopicProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TopicProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TopicProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TopicProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// *
///  Knowledge lesson metadata.
///
///  <p>Lesson id, as well as id of the parent module, are inferred from path in
///  the filesystem.
// @@protoc_insertion_point(message:fonts.LessonProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct LessonProto {
    // message fields
    // @@protoc_insertion_point(field:fonts.LessonProto.alt_ids)
    pub alt_ids: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.LessonProto.name)
    pub name: ::std::option::Option<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.LessonProto.authors)
    pub authors: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.LessonProto.reviewers)
    pub reviewers: ::std::vec::Vec<::std::string::String>,
    /// * Ids of tagged topics. 
    // @@protoc_insertion_point(field:fonts.LessonProto.topics)
    pub topics: ::std::vec::Vec<::std::string::String>,
    /// * Ids of lessons to read before this one. 
    // @@protoc_insertion_point(field:fonts.LessonProto.prev_lessons)
    pub prev_lessons: ::std::vec::Vec<::std::string::String>,
    /// * Ids of lessons to read after this one. 
    // @@protoc_insertion_point(field:fonts.LessonProto.next_lessons)
    pub next_lessons: ::std::vec::Vec<::std::string::String>,
    /// * Ids of related glossary terms. 
    // @@protoc_insertion_point(field:fonts.LessonProto.related_terms)
    pub related_terms: ::std::vec::Vec<::std::string::String>,
    /// * Brief description of the lesson. 
    // @@protoc_insertion_point(field:fonts.LessonProto.excerpt)
    pub excerpt: ::std::option::Option<::std::string::String>,
    /// * URLs of related content, for example for use in an iframe. 
    // @@protoc_insertion_point(field:fonts.LessonProto.related_content_urls)
    pub related_content_urls: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.LessonProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a LessonProto {
    fn default() -> &'a LessonProto {
        <LessonProto as ::protobuf::Message>::default_instance()
    }
}

impl LessonProto {
    pub fn new() -> LessonProto {
        ::std::default::Default::default()
    }

    // optional string name = 2;

    pub fn name(&self) -> &str {
        match self.name.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_name(&mut self) {
        self.name = ::std::option::Option::None;
    }

    pub fn has_name(&self) -> bool {
        self.name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        if self.name.is_none() {
            self.name = ::std::option::Option::Some(::std::string::String::new());
        }
        self.name.as_mut().unwrap()
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        self.name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string excerpt = 9;

    pub fn excerpt(&self) -> &str {
        match self.excerpt.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_excerpt(&mut self) {
        self.excerpt = ::std::option::Option::None;
    }

    pub fn has_excerpt(&self) -> bool {
        self.excerpt.is_some()
    }

    // Param is passed by value, moved
    pub fn set_excerpt(&mut self, v: ::std::string::String) {
        self.excerpt = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_excerpt(&mut self) -> &mut ::std::string::String {
        if self.excerpt.is_none() {
            self.excerpt = ::std::option::Option::Some(::std::string::String::new());
        }
        self.excerpt.as_mut().unwrap()
    }

    // Take field
    pub fn take_excerpt(&mut self) -> ::std::string::String {
        self.excerpt.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(10);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "alt_ids",
            |m: &LessonProto| { &m.alt_ids },
            |m: &mut LessonProto| { &mut m.alt_ids },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "name",
            |m: &LessonProto| { &m.name },
            |m: &mut LessonProto| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "authors",
            |m: &LessonProto| { &m.authors },
            |m: &mut LessonProto| { &mut m.authors },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "reviewers",
            |m: &LessonProto| { &m.reviewers },
            |m: &mut LessonProto| { &mut m.reviewers },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "topics",
            |m: &LessonProto| { &m.topics },
            |m: &mut LessonProto| { &mut m.topics },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "prev_lessons",
            |m: &LessonProto| { &m.prev_lessons },
            |m: &mut LessonProto| { &mut m.prev_lessons },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "next_lessons",
            |m: &LessonProto| { &m.next_lessons },
            |m: &mut LessonProto| { &mut m.next_lessons },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "related_terms",
            |m: &LessonProto| { &m.related_terms },
            |m: &mut LessonProto| { &mut m.related_terms },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "excerpt",
            |m: &LessonProto| { &m.excerpt },
            |m: &mut LessonProto| { &mut m.excerpt },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "related_content_urls",
            |m: &LessonProto| { &m.related_content_urls },
            |m: &mut LessonProto| { &mut m.related_content_urls },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<LessonProto>(
            "LessonProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for LessonProto {
    const NAME: &'static str = "LessonProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.alt_ids.push(is.read_string()?);
                },
                18 => {
                    self.name = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.authors.push(is.read_string()?);
                },
                34 => {
                    self.reviewers.push(is.read_string()?);
                },
                42 => {
                    self.topics.push(is.read_string()?);
                },
                50 => {
                    self.prev_lessons.push(is.read_string()?);
                },
                58 => {
                    self.next_lessons.push(is.read_string()?);
                },
                66 => {
                    self.related_terms.push(is.read_string()?);
                },
                74 => {
                    self.excerpt = ::std::option::Option::Some(is.read_string()?);
                },
                82 => {
                    self.related_content_urls.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.alt_ids {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        for value in &self.authors {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        for value in &self.reviewers {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        for value in &self.topics {
            my_size += ::protobuf::rt::string_size(5, &value);
        };
        for value in &self.prev_lessons {
            my_size += ::protobuf::rt::string_size(6, &value);
        };
        for value in &self.next_lessons {
            my_size += ::protobuf::rt::string_size(7, &value);
        };
        for value in &self.related_terms {
            my_size += ::protobuf::rt::string_size(8, &value);
        };
        if let Some(v) = self.excerpt.as_ref() {
            my_size += ::protobuf::rt::string_size(9, &v);
        }
        for value in &self.related_content_urls {
            my_size += ::protobuf::rt::string_size(10, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.alt_ids {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.name.as_ref() {
            os.write_string(2, v)?;
        }
        for v in &self.authors {
            os.write_string(3, &v)?;
        };
        for v in &self.reviewers {
            os.write_string(4, &v)?;
        };
        for v in &self.topics {
            os.write_string(5, &v)?;
        };
        for v in &self.prev_lessons {
            os.write_string(6, &v)?;
        };
        for v in &self.next_lessons {
            os.write_string(7, &v)?;
        };
        for v in &self.related_terms {
            os.write_string(8, &v)?;
        };
        if let Some(v) = self.excerpt.as_ref() {
            os.write_string(9, v)?;
        }
        for v in &self.related_content_urls {
            os.write_string(10, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> LessonProto {
        LessonProto::new()
    }

    fn clear(&mut self) {
        self.alt_ids.clear();
        self.name = ::std::option::Option::None;
        self.authors.clear();
        self.reviewers.clear();
        self.topics.clear();
        self.prev_lessons.clear();
        self.next_lessons.clear();
        self.related_terms.clear();
        self.excerpt = ::std::option::Option::None;
        self.related_content_urls.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static LessonProto {
        static instance: LessonProto = LessonProto {
            alt_ids: ::std::vec::Vec::new(),
            name: ::std::option::Option::None,
            authors: ::std::vec::Vec::new(),
            reviewers: ::std::vec::Vec::new(),
            topics: ::std::vec::Vec::new(),
            prev_lessons: ::std::vec::Vec::new(),
            next_lessons: ::std::vec::Vec::new(),
            related_terms: ::std::vec::Vec::new(),
            excerpt: ::std::option::Option::None,
            related_content_urls: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for LessonProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("LessonProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for LessonProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for LessonProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// *
///  Knowledge glossary term metadata.
///
///  <p>Term id is inferred from directory name in the filesystem.
// @@protoc_insertion_point(message:fonts.TermProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct TermProto {
    // message fields
    // @@protoc_insertion_point(field:fonts.TermProto.alt_ids)
    pub alt_ids: ::std::vec::Vec<::std::string::String>,
    // @@protoc_insertion_point(field:fonts.TermProto.name)
    pub name: ::std::option::Option<::std::string::String>,
    /// * Brief description of the glossary term. 
    // @@protoc_insertion_point(field:fonts.TermProto.excerpt)
    pub excerpt: ::std::option::Option<::std::string::String>,
    /// * Ids of related lessons. 
    // @@protoc_insertion_point(field:fonts.TermProto.related_lessons)
    pub related_lessons: ::std::vec::Vec<::std::string::String>,
    /// * URLs of related content, for example for use in an iframe. 
    // @@protoc_insertion_point(field:fonts.TermProto.related_content_urls)
    pub related_content_urls: ::std::vec::Vec<::std::string::String>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.TermProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a TermProto {
    fn default() -> &'a TermProto {
        <TermProto as ::protobuf::Message>::default_instance()
    }
}

impl TermProto {
    pub fn new() -> TermProto {
        ::std::default::Default::default()
    }

    // optional string name = 2;

    pub fn name(&self) -> &str {
        match self.name.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_name(&mut self) {
        self.name = ::std::option::Option::None;
    }

    pub fn has_name(&self) -> bool {
        self.name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_name(&mut self, v: ::std::string::String) {
        self.name = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_name(&mut self) -> &mut ::std::string::String {
        if self.name.is_none() {
            self.name = ::std::option::Option::Some(::std::string::String::new());
        }
        self.name.as_mut().unwrap()
    }

    // Take field
    pub fn take_name(&mut self) -> ::std::string::String {
        self.name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string excerpt = 3;

    pub fn excerpt(&self) -> &str {
        match self.excerpt.as_ref() {
            Some(v) => v,
            None => "",
        }
    }

    pub fn clear_excerpt(&mut self) {
        self.excerpt = ::std::option::Option::None;
    }

    pub fn has_excerpt(&self) -> bool {
        self.excerpt.is_some()
    }

    // Param is passed by value, moved
    pub fn set_excerpt(&mut self, v: ::std::string::String) {
        self.excerpt = ::std::option::Option::Some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_excerpt(&mut self) -> &mut ::std::string::String {
        if self.excerpt.is_none() {
            self.excerpt = ::std::option::Option::Some(::std::string::String::new());
        }
        self.excerpt.as_mut().unwrap()
    }

    // Take field
    pub fn take_excerpt(&mut self) -> ::std::string::String {
        self.excerpt.take().unwrap_or_else(|| ::std::string::String::new())
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(5);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "alt_ids",
            |m: &TermProto| { &m.alt_ids },
            |m: &mut TermProto| { &mut m.alt_ids },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "name",
            |m: &TermProto| { &m.name },
            |m: &mut TermProto| { &mut m.name },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
            "excerpt",
            |m: &TermProto| { &m.excerpt },
            |m: &mut TermProto| { &mut m.excerpt },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "related_lessons",
            |m: &TermProto| { &m.related_lessons },
            |m: &mut TermProto| { &mut m.related_lessons },
        ));
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "related_content_urls",
            |m: &TermProto| { &m.related_content_urls },
            |m: &mut TermProto| { &mut m.related_content_urls },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<TermProto>(
            "TermProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for TermProto {
    const NAME: &'static str = "TermProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.alt_ids.push(is.read_string()?);
                },
                18 => {
                    self.name = ::std::option::Option::Some(is.read_string()?);
                },
                26 => {
                    self.excerpt = ::std::option::Option::Some(is.read_string()?);
                },
                34 => {
                    self.related_lessons.push(is.read_string()?);
                },
                42 => {
                    self.related_content_urls.push(is.read_string()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.alt_ids {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        if let Some(v) = self.name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        if let Some(v) = self.excerpt.as_ref() {
            my_size += ::protobuf::rt::string_size(3, &v);
        }
        for value in &self.related_lessons {
            my_size += ::protobuf::rt::string_size(4, &value);
        };
        for value in &self.related_content_urls {
            my_size += ::protobuf::rt::string_size(5, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.alt_ids {
            os.write_string(1, &v)?;
        };
        if let Some(v) = self.name.as_ref() {
            os.write_string(2, v)?;
        }
        if let Some(v) = self.excerpt.as_ref() {
            os.write_string(3, v)?;
        }
        for v in &self.related_lessons {
            os.write_string(4, &v)?;
        };
        for v in &self.related_content_urls {
            os.write_string(5, &v)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> TermProto {
        TermProto::new()
    }

    fn clear(&mut self) {
        self.alt_ids.clear();
        self.name = ::std::option::Option::None;
        self.excerpt = ::std::option::Option::None;
        self.related_lessons.clear();
        self.related_content_urls.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static TermProto {
        static instance: TermProto = TermProto {
            alt_ids: ::std::vec::Vec::new(),
            name: ::std::option::Option::None,
            excerpt: ::std::option::Option::None,
            related_lessons: ::std::vec::Vec::new(),
            related_content_urls: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for TermProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("TermProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for TermProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TermProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// *
///  Knowledge contributor metadata.
///
///  <p>Contributors appear in other Knowledge metadata as authors/reviewers of
///  lessons.
// @@protoc_insertion_point(message:fonts.ContributorsProto)
#[derive(PartialEq,Clone,Default,Debug)]
pub struct ContributorsProto {
    // message fields
    // @@protoc_insertion_point(field:fonts.ContributorsProto.contributors)
    pub contributors: ::std::vec::Vec<contributors_proto::ContributorProto>,
    // special fields
    // @@protoc_insertion_point(special_field:fonts.ContributorsProto.special_fields)
    pub special_fields: ::protobuf::SpecialFields,
}

impl<'a> ::std::default::Default for &'a ContributorsProto {
    fn default() -> &'a ContributorsProto {
        <ContributorsProto as ::protobuf::Message>::default_instance()
    }
}

impl ContributorsProto {
    pub fn new() -> ContributorsProto {
        ::std::default::Default::default()
    }

    fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
        let mut fields = ::std::vec::Vec::with_capacity(1);
        let mut oneofs = ::std::vec::Vec::with_capacity(0);
        fields.push(::protobuf::reflect::rt::v2::make_vec_simpler_accessor::<_, _>(
            "contributors",
            |m: &ContributorsProto| { &m.contributors },
            |m: &mut ContributorsProto| { &mut m.contributors },
        ));
        ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContributorsProto>(
            "ContributorsProto",
            fields,
            oneofs,
        )
    }
}

impl ::protobuf::Message for ContributorsProto {
    const NAME: &'static str = "ContributorsProto";

    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
        while let Some(tag) = is.read_raw_tag_or_eof()? {
            match tag {
                10 => {
                    self.contributors.push(is.read_message()?);
                },
                tag => {
                    ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u64 {
        let mut my_size = 0;
        for value in &self.contributors {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint64_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
        self.special_fields.cached_size().set(my_size as u32);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
        for v in &self.contributors {
            ::protobuf::rt::write_message_field_with_cached_size(1, v, os)?;
        };
        os.write_unknown_fields(self.special_fields.unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn special_fields(&self) -> &::protobuf::SpecialFields {
        &self.special_fields
    }

    fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
        &mut self.special_fields
    }

    fn new() -> ContributorsProto {
        ContributorsProto::new()
    }

    fn clear(&mut self) {
        self.contributors.clear();
        self.special_fields.clear();
    }

    fn default_instance() -> &'static ContributorsProto {
        static instance: ContributorsProto = ContributorsProto {
            contributors: ::std::vec::Vec::new(),
            special_fields: ::protobuf::SpecialFields::new(),
        };
        &instance
    }
}

impl ::protobuf::MessageFull for ContributorsProto {
    fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
        descriptor.get(|| file_descriptor().message_by_package_relative_name("ContributorsProto").unwrap()).clone()
    }
}

impl ::std::fmt::Display for ContributorsProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ContributorsProto {
    type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
}

/// Nested message and enums of message `ContributorsProto`
pub mod contributors_proto {
    // @@protoc_insertion_point(message:fonts.ContributorsProto.ContributorProto)
    #[derive(PartialEq,Clone,Default,Debug)]
    pub struct ContributorProto {
        // message fields
        // @@protoc_insertion_point(field:fonts.ContributorsProto.ContributorProto.name)
        pub name: ::std::option::Option<::std::string::String>,
        /// * URL to the person's personal site. 
        // @@protoc_insertion_point(field:fonts.ContributorsProto.ContributorProto.personal_site)
        pub personal_site: ::std::option::Option<::std::string::String>,
        // special fields
        // @@protoc_insertion_point(special_field:fonts.ContributorsProto.ContributorProto.special_fields)
        pub special_fields: ::protobuf::SpecialFields,
    }

    impl<'a> ::std::default::Default for &'a ContributorProto {
        fn default() -> &'a ContributorProto {
            <ContributorProto as ::protobuf::Message>::default_instance()
        }
    }

    impl ContributorProto {
        pub fn new() -> ContributorProto {
            ::std::default::Default::default()
        }

        // optional string name = 1;

        pub fn name(&self) -> &str {
            match self.name.as_ref() {
                Some(v) => v,
                None => "",
            }
        }

        pub fn clear_name(&mut self) {
            self.name = ::std::option::Option::None;
        }

        pub fn has_name(&self) -> bool {
            self.name.is_some()
        }

        // Param is passed by value, moved
        pub fn set_name(&mut self, v: ::std::string::String) {
            self.name = ::std::option::Option::Some(v);
        }

        // Mutable pointer to the field.
        // If field is not initialized, it is initialized with default value first.
        pub fn mut_name(&mut self) -> &mut ::std::string::String {
            if self.name.is_none() {
                self.name = ::std::option::Option::Some(::std::string::String::new());
            }
            self.name.as_mut().unwrap()
        }

        // Take field
        pub fn take_name(&mut self) -> ::std::string::String {
            self.name.take().unwrap_or_else(|| ::std::string::String::new())
        }

        // optional string personal_site = 2;

        pub fn personal_site(&self) -> &str {
            match self.personal_site.as_ref() {
                Some(v) => v,
                None => "",
            }
        }

        pub fn clear_personal_site(&mut self) {
            self.personal_site = ::std::option::Option::None;
        }

        pub fn has_personal_site(&self) -> bool {
            self.personal_site.is_some()
        }

        // Param is passed by value, moved
        pub fn set_personal_site(&mut self, v: ::std::string::String) {
            self.personal_site = ::std::option::Option::Some(v);
        }

        // Mutable pointer to the field.
        // If field is not initialized, it is initialized with default value first.
        pub fn mut_personal_site(&mut self) -> &mut ::std::string::String {
            if self.personal_site.is_none() {
                self.personal_site = ::std::option::Option::Some(::std::string::String::new());
            }
            self.personal_site.as_mut().unwrap()
        }

        // Take field
        pub fn take_personal_site(&mut self) -> ::std::string::String {
            self.personal_site.take().unwrap_or_else(|| ::std::string::String::new())
        }

        pub(in super) fn generated_message_descriptor_data() -> ::protobuf::reflect::GeneratedMessageDescriptorData {
            let mut fields = ::std::vec::Vec::with_capacity(2);
            let mut oneofs = ::std::vec::Vec::with_capacity(0);
            fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
                "name",
                |m: &ContributorProto| { &m.name },
                |m: &mut ContributorProto| { &mut m.name },
            ));
            fields.push(::protobuf::reflect::rt::v2::make_option_accessor::<_, _>(
                "personal_site",
                |m: &ContributorProto| { &m.personal_site },
                |m: &mut ContributorProto| { &mut m.personal_site },
            ));
            ::protobuf::reflect::GeneratedMessageDescriptorData::new_2::<ContributorProto>(
                "ContributorsProto.ContributorProto",
                fields,
                oneofs,
            )
        }
    }

    impl ::protobuf::Message for ContributorProto {
        const NAME: &'static str = "ContributorProto";

        fn is_initialized(&self) -> bool {
            true
        }

        fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::Result<()> {
            while let Some(tag) = is.read_raw_tag_or_eof()? {
                match tag {
                    10 => {
                        self.name = ::std::option::Option::Some(is.read_string()?);
                    },
                    18 => {
                        self.personal_site = ::std::option::Option::Some(is.read_string()?);
                    },
                    tag => {
                        ::protobuf::rt::read_unknown_or_skip_group(tag, is, self.special_fields.mut_unknown_fields())?;
                    },
                };
            }
            ::std::result::Result::Ok(())
        }

        // Compute sizes of nested messages
        #[allow(unused_variables)]
        fn compute_size(&self) -> u64 {
            let mut my_size = 0;
            if let Some(v) = self.name.as_ref() {
                my_size += ::protobuf::rt::string_size(1, &v);
            }
            if let Some(v) = self.personal_site.as_ref() {
                my_size += ::protobuf::rt::string_size(2, &v);
            }
            my_size += ::protobuf::rt::unknown_fields_size(self.special_fields.unknown_fields());
            self.special_fields.cached_size().set(my_size as u32);
            my_size
        }

        fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::Result<()> {
            if let Some(v) = self.name.as_ref() {
                os.write_string(1, v)?;
            }
            if let Some(v) = self.personal_site.as_ref() {
                os.write_string(2, v)?;
            }
            os.write_unknown_fields(self.special_fields.unknown_fields())?;
            ::std::result::Result::Ok(())
        }

        fn special_fields(&self) -> &::protobuf::SpecialFields {
            &self.special_fields
        }

        fn mut_special_fields(&mut self) -> &mut ::protobuf::SpecialFields {
            &mut self.special_fields
        }

        fn new() -> ContributorProto {
            ContributorProto::new()
        }

        fn clear(&mut self) {
            self.name = ::std::option::Option::None;
            self.personal_site = ::std::option::Option::None;
            self.special_fields.clear();
        }

        fn default_instance() -> &'static ContributorProto {
            static instance: ContributorProto = ContributorProto {
                name: ::std::option::Option::None,
                personal_site: ::std::option::Option::None,
                special_fields: ::protobuf::SpecialFields::new(),
            };
            &instance
        }
    }

    impl ::protobuf::MessageFull for ContributorProto {
        fn descriptor() -> ::protobuf::reflect::MessageDescriptor {
            static descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::Lazy::new();
            descriptor.get(|| super::file_descriptor().message_by_package_relative_name("ContributorsProto.ContributorProto").unwrap()).clone()
        }
    }

    impl ::std::fmt::Display for ContributorProto {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            ::protobuf::text_format::fmt(self, f)
        }
    }

    impl ::protobuf::reflect::ProtobufValue for ContributorProto {
        type RuntimeType = ::protobuf::reflect::rt::RuntimeTypeMessage<Self>;
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x0fknowledge.proto\x12\x05fonts\"*\n\x0eKnowledgeProto\x12\x18\n\x07m\
    odules\x18\x01\x20\x03(\tR\x07modules\"n\n\x0bModuleProto\x12\x17\n\x07a\
    lt_ids\x18\x01\x20\x03(\tR\x06altIds\x12\x12\n\x04name\x18\x02\x20\x01(\
    \tR\x04name\x12\x18\n\x07excerpt\x18\x03\x20\x01(\tR\x07excerpt\x12\x18\
    \n\x07lessons\x18\x04\x20\x03(\tR\x07lessons\"9\n\nTopicProto\x12\x17\n\
    \x07alt_ids\x18\x01\x20\x03(\tR\x06altIds\x12\x12\n\x04name\x18\x02\x20\
    \x01(\tR\x04name\"\xc1\x02\n\x0bLessonProto\x12\x17\n\x07alt_ids\x18\x01\
    \x20\x03(\tR\x06altIds\x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04name\x12\
    \x18\n\x07authors\x18\x03\x20\x03(\tR\x07authors\x12\x1c\n\treviewers\
    \x18\x04\x20\x03(\tR\treviewers\x12\x16\n\x06topics\x18\x05\x20\x03(\tR\
    \x06topics\x12!\n\x0cprev_lessons\x18\x06\x20\x03(\tR\x0bprevLessons\x12\
    !\n\x0cnext_lessons\x18\x07\x20\x03(\tR\x0bnextLessons\x12#\n\rrelated_t\
    erms\x18\x08\x20\x03(\tR\x0crelatedTerms\x12\x18\n\x07excerpt\x18\t\x20\
    \x01(\tR\x07excerpt\x120\n\x14related_content_urls\x18\n\x20\x03(\tR\x12\
    relatedContentUrls\"\xad\x01\n\tTermProto\x12\x17\n\x07alt_ids\x18\x01\
    \x20\x03(\tR\x06altIds\x12\x12\n\x04name\x18\x02\x20\x01(\tR\x04name\x12\
    \x18\n\x07excerpt\x18\x03\x20\x01(\tR\x07excerpt\x12'\n\x0frelated_lesso\
    ns\x18\x04\x20\x03(\tR\x0erelatedLessons\x120\n\x14related_content_urls\
    \x18\x05\x20\x03(\tR\x12relatedContentUrls\"\xaf\x01\n\x11ContributorsPr\
    oto\x12M\n\x0ccontributors\x18\x01\x20\x03(\x0b2).fonts.ContributorsProt\
    o.ContributorProtoR\x0ccontributors\x1aK\n\x10ContributorProto\x12\x12\n\
    \x04name\x18\x01\x20\x01(\tR\x04name\x12#\n\rpersonal_site\x18\x02\x20\
    \x01(\tR\x0cpersonalSiteB#\n\x16com.google.fonts.protoB\tKnowledgeJ\xaa\
    \x19\n\x06\x12\x04\0\0f\x01\n\x08\n\x01\x0c\x12\x03\0\0\x12\nO\n\x01\x02\
    \x12\x03\x05\0\x0e\x1aE*\n\x20Proto\x20definitions\x20for\x20Fonts\x20Kn\
    owledge\x20metadata\x20in\x20the\x20filesystem.\n\n\x08\n\x01\x08\x12\
    \x03\x07\0/\n\t\n\x02\x08\x01\x12\x03\x07\0/\n\x08\n\x01\x08\x12\x03\x08\
    \0*\n\t\n\x02\x08\x08\x12\x03\x08\0*\n\"\n\x02\x04\0\x12\x04\x0b\0\x0f\
    \x01\x1a\x16*\x20Knowledge\x20metadata.\x20\n\n\n\x03\x04\0\x01\x12\x03\
    \x0b\x08\x16\n0\n\x04\x04\0\x02\0\x12\x03\r\x02\x1e\x1a\x17*\x20Module\
    \x20ids\x20in\x20order.\x20\"\n\x20Next\x20=\x202\n\n\x0c\n\x05\x04\0\
    \x02\0\x04\x12\x03\r\x02\n\n\x0c\n\x05\x04\0\x02\0\x05\x12\x03\r\x0b\x11\
    \n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\r\x12\x19\n\x0c\n\x05\x04\0\x02\0\
    \x03\x12\x03\r\x1c\x1d\nl\n\x02\x04\x01\x12\x04\x16\0\x1e\x01\x1a`*\n\
    \x20Knowledge\x20module\x20metadata.\n\n\x20<p>Module\x20id\x20is\x20inf\
    erred\x20from\x20directory\x20name\x20in\x20the\x20filesystem.\n\n\n\n\
    \x03\x04\x01\x01\x12\x03\x16\x08\x13\n\x0b\n\x04\x04\x01\x02\0\x12\x03\
    \x17\x02\x1e\n\x0c\n\x05\x04\x01\x02\0\x04\x12\x03\x17\x02\n\n\x0c\n\x05\
    \x04\x01\x02\0\x05\x12\x03\x17\x0b\x11\n\x0c\n\x05\x04\x01\x02\0\x01\x12\
    \x03\x17\x12\x19\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x17\x1c\x1d\n\x0b\
    \n\x04\x04\x01\x02\x01\x12\x03\x18\x02\x1b\n\x0c\n\x05\x04\x01\x02\x01\
    \x04\x12\x03\x18\x02\n\n\x0c\n\x05\x04\x01\x02\x01\x05\x12\x03\x18\x0b\
    \x11\n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x18\x12\x16\n\x0c\n\x05\x04\
    \x01\x02\x01\x03\x12\x03\x18\x19\x1a\n0\n\x04\x04\x01\x02\x02\x12\x03\
    \x1a\x02\x1e\x1a#*\x20Brief\x20description\x20of\x20the\x20module.\x20\n\
    \x0c\n\x05\x04\x01\x02\x02\x04\x12\x03\x1a\x02\n\n\x0c\n\x05\x04\x01\x02\
    \x02\x05\x12\x03\x1a\x0b\x11\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\x1a\
    \x12\x19\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x1a\x1c\x1d\n@\n\x04\
    \x04\x01\x02\x03\x12\x03\x1c\x02\x1e\x1a'*\x20Ids\x20of\x20constituent\
    \x20lessons\x20in\x20order.\x20\"\n\x20Next\x20=\x205\n\n\x0c\n\x05\x04\
    \x01\x02\x03\x04\x12\x03\x1c\x02\n\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\
    \x03\x1c\x0b\x11\n\x0c\n\x05\x04\x01\x02\x03\x01\x12\x03\x1c\x12\x19\n\
    \x0c\n\x05\x04\x01\x02\x03\x03\x12\x03\x1c\x1c\x1d\nj\n\x02\x04\x02\x12\
    \x04%\0)\x01\x1a^*\n\x20Knowledge\x20topic\x20metadata.\n\n\x20<p>Topic\
    \x20id\x20is\x20inferred\x20from\x20directory\x20name\x20in\x20the\x20fi\
    lesystem.\n\n\n\n\x03\x04\x02\x01\x12\x03%\x08\x12\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03&\x02\x1e\n\x0c\n\x05\x04\x02\x02\0\x04\x12\x03&\x02\n\n\
    \x0c\n\x05\x04\x02\x02\0\x05\x12\x03&\x0b\x11\n\x0c\n\x05\x04\x02\x02\0\
    \x01\x12\x03&\x12\x19\n\x0c\n\x05\x04\x02\x02\0\x03\x12\x03&\x1c\x1d\n\
    \x17\n\x04\x04\x02\x02\x01\x12\x03'\x02\x1b\"\n\x20Next\x20=\x203\n\n\
    \x0c\n\x05\x04\x02\x02\x01\x04\x12\x03'\x02\n\n\x0c\n\x05\x04\x02\x02\
    \x01\x05\x12\x03'\x0b\x11\n\x0c\n\x05\x04\x02\x02\x01\x01\x12\x03'\x12\
    \x16\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03'\x19\x1a\n\x89\x01\n\x02\
    \x04\x03\x12\x041\0C\x01\x1a}*\n\x20Knowledge\x20lesson\x20metadata.\n\n\
    \x20<p>Lesson\x20id,\x20as\x20well\x20as\x20id\x20of\x20the\x20parent\
    \x20module,\x20are\x20inferred\x20from\x20path\x20in\n\x20the\x20filesys\
    tem.\n\n\n\n\x03\x04\x03\x01\x12\x031\x08\x13\n\x0b\n\x04\x04\x03\x02\0\
    \x12\x032\x02\x1e\n\x0c\n\x05\x04\x03\x02\0\x04\x12\x032\x02\n\n\x0c\n\
    \x05\x04\x03\x02\0\x05\x12\x032\x0b\x11\n\x0c\n\x05\x04\x03\x02\0\x01\
    \x12\x032\x12\x19\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x032\x1c\x1d\n\x0b\n\
    \x04\x04\x03\x02\x01\x12\x033\x02\x1b\n\x0c\n\x05\x04\x03\x02\x01\x04\
    \x12\x033\x02\n\n\x0c\n\x05\x04\x03\x02\x01\x05\x12\x033\x0b\x11\n\x0c\n\
    \x05\x04\x03\x02\x01\x01\x12\x033\x12\x16\n\x0c\n\x05\x04\x03\x02\x01\
    \x03\x12\x033\x19\x1a\n\x0b\n\x04\x04\x03\x02\x02\x12\x034\x02\x1e\n\x0c\
    \n\x05\x04\x03\x02\x02\x04\x12\x034\x02\n\n\x0c\n\x05\x04\x03\x02\x02\
    \x05\x12\x034\x0b\x11\n\x0c\n\x05\x04\x03\x02\x02\x01\x12\x034\x12\x19\n\
    \x0c\n\x05\x04\x03\x02\x02\x03\x12\x034\x1c\x1d\n\x0b\n\x04\x04\x03\x02\
    \x03\x12\x035\x02\x20\n\x0c\n\x05\x04\x03\x02\x03\x04\x12\x035\x02\n\n\
    \x0c\n\x05\x04\x03\x02\x03\x05\x12\x035\x0b\x11\n\x0c\n\x05\x04\x03\x02\
    \x03\x01\x12\x035\x12\x1b\n\x0c\n\x05\x04\x03\x02\x03\x03\x12\x035\x1e\
    \x1f\n%\n\x04\x04\x03\x02\x04\x12\x037\x02\x1d\x1a\x18*\x20Ids\x20of\x20\
    tagged\x20topics.\x20\n\x0c\n\x05\x04\x03\x02\x04\x04\x12\x037\x02\n\n\
    \x0c\n\x05\x04\x03\x02\x04\x05\x12\x037\x0b\x11\n\x0c\n\x05\x04\x03\x02\
    \x04\x01\x12\x037\x12\x18\n\x0c\n\x05\x04\x03\x02\x04\x03\x12\x037\x1b\
    \x1c\n7\n\x04\x04\x03\x02\x05\x12\x039\x02#\x1a**\x20Ids\x20of\x20lesson\
    s\x20to\x20read\x20before\x20this\x20one.\x20\n\x0c\n\x05\x04\x03\x02\
    \x05\x04\x12\x039\x02\n\n\x0c\n\x05\x04\x03\x02\x05\x05\x12\x039\x0b\x11\
    \n\x0c\n\x05\x04\x03\x02\x05\x01\x12\x039\x12\x1e\n\x0c\n\x05\x04\x03\
    \x02\x05\x03\x12\x039!\"\n6\n\x04\x04\x03\x02\x06\x12\x03;\x02#\x1a)*\
    \x20Ids\x20of\x20lessons\x20to\x20read\x20after\x20this\x20one.\x20\n\
    \x0c\n\x05\x04\x03\x02\x06\x04\x12\x03;\x02\n\n\x0c\n\x05\x04\x03\x02\
    \x06\x05\x12\x03;\x0b\x11\n\x0c\n\x05\x04\x03\x02\x06\x01\x12\x03;\x12\
    \x1e\n\x0c\n\x05\x04\x03\x02\x06\x03\x12\x03;!\"\n.\n\x04\x04\x03\x02\
    \x07\x12\x03=\x02$\x1a!*\x20Ids\x20of\x20related\x20glossary\x20terms.\
    \x20\n\x0c\n\x05\x04\x03\x02\x07\x04\x12\x03=\x02\n\n\x0c\n\x05\x04\x03\
    \x02\x07\x05\x12\x03=\x0b\x11\n\x0c\n\x05\x04\x03\x02\x07\x01\x12\x03=\
    \x12\x1f\n\x0c\n\x05\x04\x03\x02\x07\x03\x12\x03=\"#\n0\n\x04\x04\x03\
    \x02\x08\x12\x03?\x02\x1e\x1a#*\x20Brief\x20description\x20of\x20the\x20\
    lesson.\x20\n\x0c\n\x05\x04\x03\x02\x08\x04\x12\x03?\x02\n\n\x0c\n\x05\
    \x04\x03\x02\x08\x05\x12\x03?\x0b\x11\n\x0c\n\x05\x04\x03\x02\x08\x01\
    \x12\x03?\x12\x19\n\x0c\n\x05\x04\x03\x02\x08\x03\x12\x03?\x1c\x1d\nW\n\
    \x04\x04\x03\x02\t\x12\x03A\x02,\x1a=*\x20URLs\x20of\x20related\x20conte\
    nt,\x20for\x20example\x20for\x20use\x20in\x20an\x20iframe.\x20\"\x0b\x20\
    Next\x20=\x2011\n\n\x0c\n\x05\x04\x03\x02\t\x04\x12\x03A\x02\n\n\x0c\n\
    \x05\x04\x03\x02\t\x05\x12\x03A\x0b\x11\n\x0c\n\x05\x04\x03\x02\t\x01\
    \x12\x03A\x12&\n\x0c\n\x05\x04\x03\x02\t\x03\x12\x03A)+\nq\n\x02\x04\x04\
    \x12\x04J\0T\x01\x1ae*\n\x20Knowledge\x20glossary\x20term\x20metadata.\n\
    \n\x20<p>Term\x20id\x20is\x20inferred\x20from\x20directory\x20name\x20in\
    \x20the\x20filesystem.\n\n\n\n\x03\x04\x04\x01\x12\x03J\x08\x11\n\x0b\n\
    \x04\x04\x04\x02\0\x12\x03K\x02\x1e\n\x0c\n\x05\x04\x04\x02\0\x04\x12\
    \x03K\x02\n\n\x0c\n\x05\x04\x04\x02\0\x05\x12\x03K\x0b\x11\n\x0c\n\x05\
    \x04\x04\x02\0\x01\x12\x03K\x12\x19\n\x0c\n\x05\x04\x04\x02\0\x03\x12\
    \x03K\x1c\x1d\n\x0b\n\x04\x04\x04\x02\x01\x12\x03L\x02\x1b\n\x0c\n\x05\
    \x04\x04\x02\x01\x04\x12\x03L\x02\n\n\x0c\n\x05\x04\x04\x02\x01\x05\x12\
    \x03L\x0b\x11\n\x0c\n\x05\x04\x04\x02\x01\x01\x12\x03L\x12\x16\n\x0c\n\
    \x05\x04\x04\x02\x01\x03\x12\x03L\x19\x1a\n7\n\x04\x04\x04\x02\x02\x12\
    \x03N\x02\x1e\x1a**\x20Brief\x20description\x20of\x20the\x20glossary\x20\
    term.\x20\n\x0c\n\x05\x04\x04\x02\x02\x04\x12\x03N\x02\n\n\x0c\n\x05\x04\
    \x04\x02\x02\x05\x12\x03N\x0b\x11\n\x0c\n\x05\x04\x04\x02\x02\x01\x12\
    \x03N\x12\x19\n\x0c\n\x05\x04\x04\x02\x02\x03\x12\x03N\x1c\x1d\n'\n\x04\
    \x04\x04\x02\x03\x12\x03P\x02&\x1a\x1a*\x20Ids\x20of\x20related\x20lesso\
    ns.\x20\n\x0c\n\x05\x04\x04\x02\x03\x04\x12\x03P\x02\n\n\x0c\n\x05\x04\
    \x04\x02\x03\x05\x12\x03P\x0b\x11\n\x0c\n\x05\x04\x04\x02\x03\x01\x12\
    \x03P\x12!\n\x0c\n\x05\x04\x04\x02\x03\x03\x12\x03P$%\nV\n\x04\x04\x04\
    \x02\x04\x12\x03R\x02+\x1a=*\x20URLs\x20of\x20related\x20content,\x20for\
    \x20example\x20for\x20use\x20in\x20an\x20iframe.\x20\"\n\x20Next\x20=\
    \x206\n\n\x0c\n\x05\x04\x04\x02\x04\x04\x12\x03R\x02\n\n\x0c\n\x05\x04\
    \x04\x02\x04\x05\x12\x03R\x0b\x11\n\x0c\n\x05\x04\x04\x02\x04\x01\x12\
    \x03R\x12&\n\x0c\n\x05\x04\x04\x02\x04\x03\x12\x03R)*\n\x86\x01\n\x02\
    \x04\x05\x12\x04\\\0f\x01\x1az*\n\x20Knowledge\x20contributor\x20metadat\
    a.\n\n\x20<p>Contributors\x20appear\x20in\x20other\x20Knowledge\x20metad\
    ata\x20as\x20authors/reviewers\x20of\n\x20lessons.\n\n\n\n\x03\x04\x05\
    \x01\x12\x03\\\x08\x19\n\x17\n\x04\x04\x05\x02\0\x12\x03]\x02-\"\n\x20Ne\
    xt\x20=\x202\n\n\x0c\n\x05\x04\x05\x02\0\x04\x12\x03]\x02\n\n\x0c\n\x05\
    \x04\x05\x02\0\x06\x12\x03]\x0b\x1b\n\x0c\n\x05\x04\x05\x02\0\x01\x12\
    \x03]\x1c(\n\x0c\n\x05\x04\x05\x02\0\x03\x12\x03]+,\n\x0c\n\x04\x04\x05\
    \x03\0\x12\x04`\x02e\x03\n\x0c\n\x05\x04\x05\x03\0\x01\x12\x03`\n\x1a\n\
    \r\n\x06\x04\x05\x03\0\x02\0\x12\x03a\x04\x1d\n\x0e\n\x07\x04\x05\x03\0\
    \x02\0\x04\x12\x03a\x04\x0c\n\x0e\n\x07\x04\x05\x03\0\x02\0\x05\x12\x03a\
    \r\x13\n\x0e\n\x07\x04\x05\x03\0\x02\0\x01\x12\x03a\x14\x18\n\x0e\n\x07\
    \x04\x05\x03\0\x02\0\x03\x12\x03a\x1b\x1c\n@\n\x06\x04\x05\x03\0\x02\x01\
    \x12\x03c\x04&\x1a%*\x20URL\x20to\x20the\x20person's\x20personal\x20site\
    .\x20\"\n\x20Next\x20=\x203\n\n\x0e\n\x07\x04\x05\x03\0\x02\x01\x04\x12\
    \x03c\x04\x0c\n\x0e\n\x07\x04\x05\x03\0\x02\x01\x05\x12\x03c\r\x13\n\x0e\
    \n\x07\x04\x05\x03\0\x02\x01\x01\x12\x03c\x14!\n\x0e\n\x07\x04\x05\x03\0\
    \x02\x01\x03\x12\x03c$%\
";

/// `FileDescriptorProto` object which was a source for this generated file
fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    static file_descriptor_proto_lazy: ::protobuf::rt::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::Lazy::new();
    file_descriptor_proto_lazy.get(|| {
        ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
    })
}

/// `FileDescriptor` object which allows dynamic access to files
pub fn file_descriptor() -> &'static ::protobuf::reflect::FileDescriptor {
    static generated_file_descriptor_lazy: ::protobuf::rt::Lazy<::protobuf::reflect::GeneratedFileDescriptor> = ::protobuf::rt::Lazy::new();
    static file_descriptor: ::protobuf::rt::Lazy<::protobuf::reflect::FileDescriptor> = ::protobuf::rt::Lazy::new();
    file_descriptor.get(|| {
        let generated_file_descriptor = generated_file_descriptor_lazy.get(|| {
            let mut deps = ::std::vec::Vec::with_capacity(0);
            let mut messages = ::std::vec::Vec::with_capacity(7);
            messages.push(KnowledgeProto::generated_message_descriptor_data());
            messages.push(ModuleProto::generated_message_descriptor_data());
            messages.push(TopicProto::generated_message_descriptor_data());
            messages.push(LessonProto::generated_message_descriptor_data());
            messages.push(TermProto::generated_message_descriptor_data());
            messages.push(ContributorsProto::generated_message_descriptor_data());
            messages.push(contributors_proto::ContributorProto::generated_message_descriptor_data());
            let mut enums = ::std::vec::Vec::with_capacity(0);
            ::protobuf::reflect::GeneratedFileDescriptor::new_generated(
                file_descriptor_proto(),
                deps,
                messages,
                enums,
            )
        });
        ::protobuf::reflect::FileDescriptor::new_generated_2(generated_file_descriptor)
    })
}
